In [2]:
import torch

## Tensors

In [21]:
# Simple python list
a = [1.0, 2.0, 1.0]
print(a[0])
a[2] = 3.0
print(a)

1.0
[1.0, 2.0, 3.0]


In [25]:
# Create Pytorch tensor
a = torch.ones(3)

In [26]:
# Indexing
a[1]

tensor(1.)

In [27]:
# Convert to float
float(a[1])

1.0

In [28]:
# Manipulate content
a[2] = 2.0
a

tensor([1., 1., 2.])

In [12]:
# Triangle coordinates with X's in even and Y's in odds
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [29]:
# Create tensor from 1D list
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [30]:
# Get coordinates of first triangle vertex
float(points[0]), float(points[1])

(4.0, 1.0)

In [16]:
# 2D version
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [31]:
# Get tensor shape
points.shape

torch.Size([6])

In [32]:
# Create 2D tensor with 0s
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## Indexing

In [33]:
# 2D indexing
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points[0, 1]

tensor(1.)

In [34]:
# 1D indexing on 2D tensor
points[0]

tensor([4., 1.])

In [40]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [41]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [42]:
points[1:, 0]

tensor([5., 2.])

In [43]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

## Data Types

In [3]:
double_points = torch.ones(10, 2, dtype=torch.double) # or torch.float64, float32 is default
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short) # or torch.int16, int64 is default

In [4]:
short_points.dtype

torch.int16

In [7]:
# Type casting
do_points = torch.zeros(10, 2).double()
so_points = torch.ones(10, 2).short()

# to() also checks whether conversion is necessary
# but .double() and so on are shorthands for to()
new_do_points = torch.zeros(10, 2).to(torch.double)
new_so_points = torch.ones(10, 2).to(torch.short)

In [8]:
# Computations cast to larger type
points_64 = torch.rand(5, dtype=torch.double)   # 64-bit
points_short = points_64.to(torch.short)        # 32-bit
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

## Transpose

In [9]:
# Transpose
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [11]:
# Or
a_t = a.transpose(0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

## Storage

In [14]:
# Tensors are stored sequentially in memory
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [15]:
# Direct access, only 1D for any tensor shape
points_storage = points.storage()
points_storage[2]

5.0

In [16]:
# Modifying storage modifies the tensor as well
points_storage[2] = 3.0
points

tensor([[4., 1.],
        [3., 3.],
        [2., 1.]])

In [17]:
# Functions with trailing underscore are inplace
a = torch.ones(3, 2)
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## Tensor Metadata

In [18]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]

# Two elements in memory have to be skipped to get to the second point
second_point.storage_offset()

2

In [19]:
# Same information
second_point.size(), second_point.shape

(torch.Size([2]), torch.Size([2]))

In [20]:
# Number of elements that need to be skipped in memory to get to next element of some dimension
points.stride()

(2, 1)

In [21]:
# Changing sub tensors also changes the main tensor
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [22]:
# We can clone to mitigate this problem
second_point_c = points[1].clone()
second_point_c[0] = 15.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

## Transpose under the hood

In [52]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points, points_t

(tensor([[4., 1.],
         [5., 3.],
         [2., 1.]]),
 tensor([[4., 5., 2.],
         [1., 3., 1.]]))

In [53]:
id(points.storage()) == id(points_t.storage())

False

In [54]:
# The memory should still be the same, but it is accessed differently
points.stride(), points_t.stride()

((2, 1), (1, 2))

In [55]:
# Multidimensional Transposing
some_t = torch.ones(2, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape, transpose_t.shape

(torch.Size([2, 4, 5]), torch.Size([5, 4, 2]))

In [56]:
# Contiguous tensors are stored such that they can be accessed efficiently
points.is_contiguous()

True

In [57]:
points_t.is_contiguous()

False

In [59]:
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [61]:
# The transposed points tensor is stored in such a way
# that we have to skip between rows when reading
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [63]:
points_t.stride()

(1, 2)

In [62]:
# Contiguous method returns a contiguous tensor
points_c = points_t.contiguous()
points_c.is_contiguous()

True

In [65]:
points_c

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [64]:
# No jumping between objects required anymore
# stride[0] = jump 3 to next row, stride[1] = jump 1 to next column
points_c.stride()

(3, 1)

In [66]:
points_c.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [67]:
points.is_contiguous()

True

## Moving to GPUs

In [71]:
# Use device argument
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

# Or copy
points_gpu_ = points.to(device='cuda')

In [72]:
# If multiple GPUs are present, zero indexing for GPU selection
points_gpu_0 = points.to(device='cuda:0')

In [74]:
points_gpu = points_gpu * 2 # Carried out on the GPU

In [75]:
# Move back to CPU
points_cpu = points_gpu.to(device='cpu')
points_cpu

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]])

In [77]:
# Also can use shorthand methods
points_sh_gpu = points_cpu.cuda()       # Default is 0
points_sh_gpu_0 = points_cpu.cuda(0)    # Choose which GPU
points_sh_cpu = points_sh_gpu.cpu()

# to() however allows switching datatype and device at the same time

## Numpy Interoperability

In [79]:
# To switch to numpy, use numpy() method
points = torch.zeros(2, 3)
points_np = points.numpy()
type(points_np)

numpy.ndarray

In [80]:
points

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [81]:
# Both arrays share the same memory, changes are reflected in both of them
points_np[1] = 2.0
points

In [84]:
# Can not convert, if tensor is on GPU
points_gpu = torch.zeros(2, 3, device='cuda')
points_gpu_np = points_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [90]:
# Convert from numpy array to tensor
points_ten = torch.from_numpy(points_np)

# And again, changes are reflected in both data structures
points_ten[1, 2] = 10.0
points_np

array([[ 0.,  0.,  0.],
       [ 2.,  2., 10.]], dtype=float32)

## Serialization of tensors

In [95]:
# Save and load, the file format is not interoperable
torch.save(points, 'data/tensor.t')
loaded_tensor = torch.load('data/tensor.t')
loaded_tensor

tensor([[ 0.,  0.,  0.],
        [ 2.,  2., 10.]])

In [98]:
import h5py

# Save in a format that is interoperable
f = h5py.File('data/points.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [102]:
# Load
f = h5py.File('data/points.hdf5', 'r')

# coords is used as a key
dset_loaded = f['coords']

# The data is only loaded from the disk when it is required
last_points = torch.from_numpy(dset_loaded[-2:])
f.close()

## Exercises

### Exercise 1

The tensor will have shape (9), stride (1) and offset (0).

In [106]:
a = torch.tensor(list(range(9)))
a.shape, a.stride(), a.storage_offset()

(torch.Size([9]), (1,), 0)

In [108]:
b = a.view(3, 3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [110]:
b.storage().data_ptr() == a.storage().data_ptr()

True

Size will be (2, 2), stride (2, 1) and offset (4).

In [111]:
c = b[1:, 1:]
c.shape, c.stride(), c.storage_offset()

(torch.Size([2, 2]), (3, 1), 4)

### Exercise 2

In [112]:
a = torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [113]:
a.sqrt()

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])

In [114]:
a.cos()

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [117]:
torch.cos(a)

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [116]:
a.sqrt_()

RuntimeError: result type Float can't be cast to the desired output type Long